[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
no_match_path = "*/integration/*"
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}, {access = "read-write", path = ".artifacts/"},{ access = "read-write", path = "out/" }, { access = "read", path = "./test/foundry-tests/interop.json"}]
optimizer_runs = 1000000
solc = "0.8.24"

[profile.integration]
no_match_path = ""
match_path = "*/integration/*"

[profile.lite.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = 'xca'
